spring:
  application:
    name: turbine
server:
  port: 8989
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: RIBBON-CONSUMER
  cluster-name-expression: "'default'"
