spring:
  application:
    name: api-gateway

server:
  port: 5555

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    cn.aki.demo: debug

zuul:
  routes:
    #名称自定义
    #通过url,不需要eureka
    api-url:
      path: /api-url/**
      url: http://localhost:9001/
    #通过eureka
    api-c:
      path: /c/**
      serviceId: hello-service
    api-f:
      path: /f/**
      serviceId: feign-consumer
    #本地跳转
    forward:
      path: /l/**
      url: forward:/local
    #默认自动实现了service-name：/service-name/**
    #hello-service: /hello-service/**

  #path开头与前缀相同时url映射存在bug
#  prefix: /api

  #不自动创建路由,防止所有接口都暴露
  ignored-services: '*'






