spring:
  application:
    name: hello-service
  sleuth:
    sampler:
      percentage: 1 #默认0.1
  #仅基于http时有效
#  zipkin:
#    base-url: http://localhost:9411/ #默认
  rabbitmq:
    username: springcloud
    password: 123qwe
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #默认
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
server:
  port: 8081

#日志
logging:
  level:
    cn.aki.demo: debug