spring:
  application:
    name: ribbon-consumer
  sleuth:
    sampler:
      percentage: 1 #默认0.1
  rabbitmq:
    username: springcloud
    password: 123qwe
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9001

#日志
logging:
  level:
    cn.aki.demo: debug

