spring:
  application:
    name: feign-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9001

#日志
logging:
  level:
    cn.aki.demo: debug

