spring:
  rabbitmq:
    username: springcloud
    password: 123qwe
  cloud:
    stream:
      bindings:
        input:
          #分组
          group: group
        # 自定义,input和output的destination相同时实现信息交互
        custom-input:
          destination: custom-topic
        custom-output:
          destination: custom-topic

server:
  port: 8081
