spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/akileecn/spring-cloud-config.git
          search-paths: /config-repo
          #username:
          #password:

server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#日志
logging:
  level:
    cn.aki.demo: debug
